import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../scss/Home.module.scss";
// import  "../scss/global.scss";

import {Button} from "semantic-ui-react"
import Form from "./home/home";
// import "@/scss/global.scss"



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

      <Form/>

      

      </main>

    
    </>
  );
}
